### ISSUE TITLE
 standardize_column_names: file name deos not match function name.

### ISSUE THREAD

**Issue by Degoot-AM** [epiverse-trace/cleanepi#50]
Function name: `standardize_column_names(...)`
File name: `column_name_standardidation.R`. It is good to keep both the same.

**Comment by Karim-Mane** [comment]
@Degoot-AM  - The file naming convention that I am using is such that the `file name` matches the `module name` in the package design vignette.

However, the name of the main function in every module can be different from the file name. This is because, I am using "action verbs" to define what the function is doing and give it a bit more context.
